// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bffnaqbzwmndqajbouna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmZm5hcWJ6d21uZHFhamJvdW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NTAxNTksImV4cCI6MjA4ODAyNjE1OX0.4qwSknv7hBVQ6qHbBXL7vnvP4-9vygv6g1lbUnJqVHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);